routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('group-call',array('as' => 'group-call','uses' => 'ClassRoomController@multiconnection_group_call'));
Route::get('scholars-group-call',array('as' => 'scholars-group-call','uses' => 'ClassRoomController@scholars_multiconnection_group_call'));

Route::get('/group-conference',array('as' => 'group-conference','uses' => 'ClassRoomController@group_conference'));

Route::get('scholars-room', array('as' => 'scholars-room', 'uses' => 'ClassRoomController@scholars_room'));

Route::get('my-room', array('as' => 'my-room', 'uses' => 'ClassRoomController@my_room'));

// Route 2
Route::get('/classroom', 'ChatController@chat_room_list');

Route::post('/create-room', 'ChatController@create_room');

Route::post('/add-user-to-room', 'ChatController@add_user_to_room');

Route::get('/enter-room/{id}', 'ChatController@enter_room_by_id');

Route::get('/home', 'ChatController@login')->name('home');

Route::get('/login', 'ChatController@login')->name('login');

Route::post('/chat', 'ChatController@chat')->name('chat');

Route::get('/test', 'ChatController@test')->name('test');

Route::resource('/rooms', 'RoomController');

Route::get('/setting_room/{id}', 'RoomController@setting_room')->name('setting_room');
Route::post('/setting_generate', 'RoomController@setting_generate')->name('setting_generate');

resources/views/chat_2_globalset.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>chat</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style type="text/css">
          html { height: 100%; }
          body { height: 100%; margin: 0; background: #333; text-align: center; }
          .video { height: 200px; margin-top: 5%; background: #000; }
          .localVideo { width: 150px; position: absolute; right: 1.1em; bottom: 1em; border: 1px solid #333; background: #000; }
          #callButton {
            position: absolute;
            /* display: none; */
            left: 50%;
            font-size: 2em;
            bottom: 60%;
            border-radius: 1em;
        }
          
        </style>
    </head>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>

    <body>
        <div class="flex-center position-ref full-height">
            <div class="content">
              <h1 style="color:white;">{{$nick}}</h1>
              <br>
              <video id="localVideo-{{$nick}}"  class="localVideo" autoplay muted></video>

              <button id="callButton" onclick="createOffer()">✆</button>
              <video id="remoteVideo-user1" class='video' autoplay></video>
              <video id="remoteVideo-user2" class='video' autoplay></video>
              <video id="remoteVideo-user3" class='video' autoplay></video>

            </div>
        </div>

        <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        First PC, first offer: <span id="11"></span><br/>
        First PC, second offer: <span id="12"></span><br/>
        Second PC, first offer: <span id="21"></span><br/>
        Second PC, second offer: <span id="22"></span><br/> -->
    </body>
    <script>

      var PeerConnection = window.mozRTCPeerConnection || window.webkitRTCPeerConnection;
      var IceCandidate = window.mozRTCIceCandidate || window.RTCIceCandidate;
      var SessionDescription = window.mozRTCSessionDescription || window.RTCSessionDescription;
      navigator.getUserMedia = navigator.getUserMedia || navigator.mozGetUserMedia || navigator.webkitGetUserMedia;

      // var pc_user1;
      // var pc_user2;
      // var pc_user3;

      var pc;

      console.log('mypc', pc);


      // Step 1. getUserMedia
    //   navigator.mediaDevices.getUserMedia(
    //       { audio: true, video: true },
    //  //   { video: true },
    //     gotStream,
    //     function(error) { console.log(error) }
    //   );


      if (navigator.mediaDevices.getUserMedia) {
        console.log('here');
    navigator.mediaDevices.getUserMedia({  audio: true, video: true })
        .then(function (stream) {
            console.log(stream);
            console.log('mystream', stream)
          gotStream(stream)
      })
        .catch(function (e) { e.name + ": " + e.message; });      

      }

      function gotStream(stream) {

        console.log('hello stream function', getUser());
        console.log('hello', "localVideo-{{$nick}}");
      //  console.log('link', window.URL.createObjectURL(stream));
        document.getElementById("callButton").style.display = 'inline-block';
        document.getElementById("localVideo-{{$nick}}").srcObject = stream;

          //eval('pc_' + getUser()) = new PeerConnection(null);

          const servers = {
            // iceServers: [
            //   //        {urls: 'stun:stun.l.google.com:19302'},
            //   //        {urls: stunServers},
            //   {
            //     urls: 'turn:52.88.28.2:3478',
            //     username: 'turnuser',
            //     credential: 'turn.pass'
            //   }
            // ]

            iceServers: [{
            //  urls: 'stun:stun.l.google.com:19302'

          //  urls: 'turn:192.168.0.102:3478',
          //        username: 'test',
          //        credential: 'test'

           //  urls: 'turn:192.168.0.119:3478',

                //  urls: 'turn:webrtc-test.ru',
                //  username: 'test',
                //  credential: 'test'

                urls: 'turn:52.88.28.2:3478',
                username: 'turnuser',
                credential: 'turn.pass'
             }]
          };

          console.log('server_conf', servers);


          // pc_user1 = new PeerConnection(servers);
          // pc_user2 = new PeerConnection(servers);

          
          // eval('pc_' + getUser()).addStream(stream);
          // eval('pc_' + getUser()).onicecandidate = eval('gotIceCandidate_' + getUser());
          // eval('pc_' + getUser()).onaddstream = eval('gotRemoteStream_' + getUser());

          pc = new PeerConnection(servers);
          pc.addStream(stream);
          pc.onicecandidate = gotIceCandidate_user;
          pc.onaddstream = gotRemoteStream_user;


          // pc_user1 = new PeerConnection(servers);
          // pc_user1.addStream(stream);
          // pc_user1.onicecandidate = gotIceCandidate_user1;
          // pc_user1.onaddstream = gotRemoteStream_user1;

          // console.log('pc_user11', pc_user1);
          
          // pc_user2 = new PeerConnection(servers);
          // pc_user2.addStream(stream);
          // pc_user2.onicecandidate = gotIceCandidate_user2;
          // pc_user2.onaddstream = gotRemoteStream_user2;

          // console.log('pc_user22', pc_user2);
          // //
          // pc_user3 = new PeerConnection(servers);
          // pc_user3.addStream(stream);
          // pc_user3.onicecandidate = gotIceCandidate_user3;
          // pc_user3.onaddstream = gotRemoteStream_user3;


      }

      function createOffer() {

        //  console.log('create offer for', getUser());


              pc.createOffer(
              gotLocalDescription_user,
                function(error) { console.log(error) },
                { 'mandatory': { 'OfferToReceiveAudio': true, 'OfferToReceiveVideo': true } }
             );


          // eval('pc_' + getUser()).createOffer(
          //   eval('gotLocalDescription_' + getUser()),
          //   function(error) { console.log(error) },
          //   { 'mandatory': { 'OfferToReceiveAudio': true, 'OfferToReceiveVideo': true } }
          // );

          // pc_user1.createOffer(
          //   gotLocalDescription_user1,
          //   function(error) { console.log(error) },
          //   { 'mandatory': { 'OfferToReceiveAudio': true, 'OfferToReceiveVideo': true } }
          // );
          //  pc_user2.createOffer(
          //    gotLocalDescription_user2,
          //    function(error) { console.log(error) },
          //    { 'mandatory': { 'OfferToReceiveAudio': true, 'OfferToReceiveVideo': true } }
          //  );
        console.log("WE CALLED!")
      }


        function createAnswer_user() {
          console.log("createAnswer_user");
           pc.createAnswer(
             gotLocalDescription_user,
             function(error) { console.log(error) },
             { 'mandatory': { 'OfferToReceiveAudio': true, 'OfferToReceiveVideo': true } }
           );
           console.log("WE ANSWERED!");
        }

        function gotLocalDescription_user(description){
          console.log('localDesc_user', description)
          pc.setLocalDescription(description);
          sendMessage(description);
        }

        function gotIceCandidate_user(event){
          if (event.candidate) {
            sendMessage({
              type: 'candidate',
              label: event.candidate.sdpMLineIndex,
              id: event.candidate.sdpMid,
              candidate: event.candidate.candidate
            });
          }
        }

        function gotRemoteStream_user(event){
          console.log('getRmoteStream form user', event.stream)

          document.getElementById("remoteVideo-user3").srcObject = event.stream;

        }




        function getUser() {
          if("{{$nick}}" == "user1")
            return "user2";

          return "user1";
        }


function createAnswer_user2() {
  console.log("createAnswer_user2");
   pc_user2.createAnswer(
     gotLocalDescription_user2,
     function(error) { console.log(error) },
     { 'mandatory': { 'OfferToReceiveAudio': true, 'OfferToReceiveVideo': true } }
   );
   console.log("WE ANSWERED!");
}

function gotLocalDescription_user2(description){
  console.log('localDESC_user2', description);
  pc_user2.setLocalDescription(description);
   console.log('pc_user2_user2', pc_user2);
  sendMessage(description, getUser());
}

function gotIceCandidate_user2(event){
  if (event.candidate) {
    sendMessage({
      type: 'candidate',
      label: event.candidate.sdpMLineIndex,
      id: event.candidate.sdpMid,
      candidate: event.candidate.candidate
    }, getUser());
  }
}

function gotRemoteStream_user2(event){
  console.log('remote user stream user2', event.stream)

  document.getElementById("remoteVideo-user2").srcObject = event.stream;

}


// For User 3
function createAnswer_user3() {
  console.log("createAnswer_user3");
   pc_user3.createAnswer(
     gotLocalDescription_user3,
     function(error) { console.log(error) },
     { 'mandatory': { 'OfferToReceiveAudio': true, 'OfferToReceiveVideo': true } }
   );
   console.log("WE ANSWERED!");
}

function gotLocalDescription_user3(description){
  console.log('localDESC_user3', description);
  pc_user3.setLocalDescription(description);
   console.log('pc_user3_user3', pc_user3);
  sendMessage(description, getUser());
}

function gotIceCandidate_user3(event){
  if (event.candidate) {
    sendMessage({
      type: 'candidate',
      label: event.candidate.sdpMLineIndex,
      id: event.candidate.sdpMid,
      candidate: event.candidate.candidate
    }, getUser());
  }
}

function gotRemoteStream_user3(event){
  console.log('remote user stream user3', event.stream)

  document.getElementById("remoteVideo-user3").srcObject = event.stream;

}





      // WebSocket
   //   var conn = new WebSocket('wss://webrtc.local:443/wss2/');
 //  var conn = new WebSocket("wss://webrtc-test.ru/wss2/");
  //  var conn = new WebSocket('wss:/scholars-home.org/chatsocket');

    var conn = new WebSocket('ws:/localhost:8080');
    console.log('websocekt', conn)
      conn.open = function(e){
        console.log("Connection established!", e);
      }

    // Let us open a web socket
              //  var conn = new WebSocket("ws://localhost:9998/echo");
				
              //  conn.onopen = function() {
                  
              //     // Web Socket is connected, send data using send()
              //     conn.send("Message to send");
              //     alert("Message is sent...");
              //  };

      conn.onmessage = function(str){
        //obj = Object.create(message[0]);
        //console.log("we got str: " + str.data);

        console.log('I am in message section');


        message = JSON.parse(str.data);

        console.log('I amkk', message);


          // if(message.dst === "{{$nick}}")
          // {
         //   var src = message.src;
            var variable = 'pc';

            console.log(message);
            if (message.type === 'offer') {
                console.log('message.type', message.type );
                eval(variable).setRemoteDescription(new SessionDescription(message));
                //createAnswer_user1();
                eval("createAnswer_user" + '()');
            }
            else if (message.type === 'answer') {

              eval(variable).setRemoteDescription(new SessionDescription(message));
            }
            else if (message.type === 'candidate') {
                //alert(3);
                var candidate = new IceCandidate({sdpMLineIndex: message.label, candidate: message.candidate});
                eval(variable).addIceCandidate(candidate);
                //alert(4);
            }
    //      }


      }
      //
      // function send(){
      //     var data = 'Data for sending: ' + Math.random();
      //     conn.send(data);
      //     console.log('Sent: ' + data);
      // }

      function sendMessage(message){
        var str = JSON.stringify(message);
        str = str.replace("{", '{"src":"{{$nick}}", "dst":"' + 'all users' + '",');
       console.log("We sending: ", str);
          console.log("conn: ", conn);
          conn.send(str);
      }

      // function sendMessage(message){
      //   var str = JSON.stringify(message);
      //  console.log("We sending: ", str);
      //     //console.log("we sending: ", str);
      //     conn.send(str);
      // }

    </script>
</html>

resources/views/chat_back.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>chat</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style type="text/css">
          html { height: 100%; }
          body { height: 100%; margin: 0; background: #333; text-align: center; }
          .video { height: 200px; margin-top: 5%; background: #000; }
          .localVideo { width: 150px; position: absolute; right: 1.1em; bottom: 1em; border: 1px solid #333; background: #000; }
          #callButton { position: absolute; display: none; left: 50%; font-size: 2em; bottom: 5%; border-radius: 1em; }
        </style>
    </head>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>

    <body>
        <div class="flex-center position-ref full-height">
            <div class="content">
              <video id="localVideo-{{$nick}}"  class="localVideo" autoplay muted></video>

              <button id="callButton" onclick="createOffer()">✆</button>
                @foreach($users as $user)
                  @if($user == $nick)
                    @continue;
                  @endif
                  <video id="remoteVideo-{{$user}}" class='video' autoplay></video>
                @endforeach
                <!-- <button onclick="send();">Send</button> -->
            </div>
        </div>
    </body>
    <script>

      var PeerConnection = window.mozRTCPeerConnection || window.webkitRTCPeerConnection;
      var IceCandidate = window.mozRTCIceCandidate || window.RTCIceCandidate;
      var SessionDescription = window.mozRTCSessionDescription || window.RTCSessionDescription;
      navigator.getUserMedia = navigator.getUserMedia || navigator.mozGetUserMedia || navigator.webkitGetUserMedia;

      @foreach($users as $user)
        @if($user == $nick)
          @continue;
        @endif
        var pc{{$user}};
      @endforeach


      // Step 1. getUserMedia
      navigator.getUserMedia(
        //  { audio: true, video: true },
        { video: true },
        gotStream,
        function(error) { console.log(error) }
      );

      function gotStream(stream) {
        document.getElementById("callButton").style.display = 'inline-block';
        document.getElementById("localVideo-{{$nick}}").src = URL.createObjectURL(stream);
        console.log(URL.createObjectURL(stream));
        @foreach($users as $user)
          @if($user == $nick)
            @continue;
          @endif
          pc{{$user}} = new PeerConnection(null);
          pc{{$user}}.addStream(stream);
          pc{{$user}}.onicecandidate = gotIceCandidate{{$user}};
          pc{{$user}}.onaddstream = gotRemoteStream{{$user}};
        @endforeach

      }

      function createOffer() {
        @foreach($users as $user)
          @if($user == $nick)
            @continue;
          @endif
          pc{{$user}}.createOffer(
            gotLocalDescription{{$user}},
            function(error) { console.log(error) },
            { 'mandatory': { 'OfferToReceiveAudio': true, 'OfferToReceiveVideo': true } }
          );
        @endforeach
        console.log("WE CALLED!")
      }

      // Step 2. createOffer
      @foreach($users as $user)
        @if($user == $nick)
          @continue;
        @endif


        function createAnswer{{$user}}() {
           pc{{$user}}.createAnswer(
             gotLocalDescription{{$user}},
             function(error) { console.log(error) },
             { 'mandatory': { 'OfferToReceiveAudio': true, 'OfferToReceiveVideo': true } }
           );
           console.log("WE ANSWERED!");
        }

        function gotLocalDescription{{$user}}(description){
        //  description.nick="{{$user}}";
          pc{{$user}}.setLocalDescription(description);
          console.log("description: ", description);
          sendMessage(description);
        }

        function gotIceCandidate{{$user}}(event){
          if (event.candidate) {
            sendMessage({
              type: 'candidate',
          //    nick: "{{$user}}",
              label: event.candidate.sdpMLineIndex,
              id: event.candidate.sdpMid,
              candidate: event.candidate.candidate
            });
          }
        }

        function gotRemoteStream{{$user}}(event){
          console.log("gotRemoteStream{{$user}}");
          document.getElementById("remoteVideo-{{$user}}").src = URL.createObjectURL(event.stream);

        }
      @endforeach




      // function createAnswer() {
      //    pc.createAnswer(
      //      gotLocalDescription,
      //      function(error) { console.log(error) },
      //      { 'mandatory': { 'OfferToReceiveAudio': true, 'OfferToReceiveVideo': true } }
      //    );
      //    console.log("WE ANSWERED!");
      // }







      // WebSocket
      var conn = new WebSocket('wss://webrtc.local:443/wss2/');
      conn.open = function(e){
        console.log("Connection established!");;
      }

      conn.onmessage = function(str){
        //obj = Object.create(message[0]);
        //console.log("we got str: " + str.data);

        //console.log("we got data: " + str.data);
        message = JSON.parse(str.data);
        console.log("NICK: " + message.nick);
        @foreach($users as $user)
          @if($user == $nick)
            @continue;
          @endif
          if (message.type === 'offer' && message.nick === '{{$user}}') {
              pc{{$user}}.setRemoteDescription(new SessionDescription(message));
              createAnswer{{$user}}();
            }
            else if (message.type === 'answer' && message.nick === '{{$user}}') {
              console.log("message.type === 'answer'", message.nick, '=== {{$user}}');
            //  pc{{$user}}.setRemoteDescription(new SessionDescription(message));
              pc{{$user}}.setRemoteDescription(new SessionDescription(message));
            }
            else if (message.type === 'candidate' && message.nick === '{{$user}}') {
              var candidate = new IceCandidate({sdpMLineIndex: message.label, candidate: message.candidate});
              pc{{$user}}.addIceCandidate(candidate);
            }

        @endforeach
      }
      //
      // function send(){
      //     var data = 'Data for sending: ' + Math.random();
      //     conn.send(data);
      //     console.log('Sent: ' + data);
      // }

      function sendMessage(message){
        var str = JSON.stringify(message);
        str = str.replace("{", '{"nick":"{{$nick}}",');
      // console.log("We sending: ", str);
          //console.log("we sending: ", str);
          conn.send(str);
      }

      // function sendMessage(message){
      //   var str = JSON.stringify(message);
      //  console.log("We sending: ", str);
      //     //console.log("we sending: ", str);
      //     conn.send(str);
      // }

    </script>
</html>

resources/views/login.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Login</title>

    </head>
    <body>
        <div class="flex-center position-ref full-height">
            <div class="content">
                <div class="title m-b-md">
                    Laravel2
                </div>
                @foreach($users as $key => $value)
                <form method="post" action="{{route('chat')}}">
                  {{ csrf_field() }}
                  <input type="text" name="nick" placeholder="nick" value="{{$value}}"><br>
                  <input type="text" name="pass" value="{{$key}}"><br>
                  <input type="text" name="fio" value=""><br>

                    <label><input type="radio" name="camera" value="1" checked="checked" />camera</label><br>
                    <label><input type="radio" name="camera" value="2" />microphone</label><br>

                  <input type="submit" value="Join">
                </form>
                @endforeach
            </div>
        </div>
    </body>

</html>

resources/views/room.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <!-- Styles -->
        <script src="{{ URL::asset('js/jquery-3.2.1.min.js')}}" ></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="flex-center position-ref full-height">

            <div class="content">
              <div class="row">

              </div>
              <div class="row">
                <div class="col-xs-7 col-md-4 col-xs-offset-8 col-md-offset-4">
                  <h1>{{$room->name}}</h1>

                  <form action="{{route('setting_generate')}}" method="post">
                    {{ csrf_field() }}
                    <input type="hidden" name="id" value="{{$room->id}}">
                    <div class="input-group">
                      <label>Количество пользователей в комнате</label>
                      <input type="text" id="count_users" name="count_users" value="{{$room->count_users}}">
                    </div>

                    <div class="input-group">
                    <input type='submit' class="btn btn-success" value='generate'>
                    </div>
                  </form>

                </div>
              </div>
              <div class="row">
                <div class="col-xs-7 col-md-4 col-xs-offset-8 col-md-offset-4">
                  <table class="table table-striped">
                    <tr>
                      <th>nick</th>
                      <th>pass</th>
                    </tr>
                    @foreach($room->setting as $setting)
                    <tr>
                      <td>{{$setting->nick}}</td>
                      <td>
                        {{ $setting->pass }}
                      </td>
                    </tr>
                    @endforeach
                  </table>
                </div>
              </div>

            </div>


        </div>
    </body>
    <script>

    </script>
</html>

resources/views/rooms.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <!-- Styles -->
        <script src="{{ URL::asset('js/jquery-3.2.1.min.js')}}" ></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="flex-center position-ref full-height">

            <div class="content">
              <div class="row">
                <div class="col-xs-7 col-md-4 col-xs-offset-8 col-md-offset-4">
                  <form class="" id="create" action="{{route('rooms.store')}}" method="post">
                    <div class="input-group">
                      <span class="input-group-addon" id="basic-addon1">+</span>
                      {{ csrf_field() }}
                      <input type="text" class="form-control" placeholder="room" aria-describedby="basic-addon1" name='room'>
                      <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Add">
                      </span>
                    </div>
                  </form>
                </div>
              </div>
              <div class="row">
                <div class="col-xs-7 col-md-4 col-xs-offset-8 col-md-offset-4">
                  <table class="table table-striped">
                    <tr>
                      <th>Name</th>
                      <th>Remove</th>
                      <th>Settings</th>
                    </tr>
                    @foreach($rooms as $room)
                    <tr>
                      <td>{{ $room->name }}</td>
                      <td>
                        <form action="{{route('rooms.destroy',['id' => $room->id])}}" method="post">
                          {{ csrf_field() }}
                          <input type='hidden' name="_method" value='DELETE'>
                          <input type='submit' class="btn btn-danger" value='delete'>
                        </form>
                      </td>
                      <td>
                        <a href="{{ route('setting_room',['id' => $room->id]) }}" class="btn btn-success">Settings</a>
                      </td>
                    </tr>
                    @endforeach
                  </table>
                </div>
              </div>

            </div>


        </div>
    </body>
    <script>

    </script>
</html>